name:       paychan-datastore
version:    '0.1.0.0'
synopsis:
description:  Please see README.md
category:     Database Network Google
author:       Rune K. Svendsen
maintainer:   runesvend@gmail.com
copyright:    2016 Rune K. Svendsen
license:      CC0
github:       runeksvendsen/paychan-datastore

default-extensions:
- OverloadedStrings
- MultiParamTypeClasses
- TypeSynonymInstances
- FlexibleInstances
- FlexibleContexts
- FunctionalDependencies
- DataKinds
- ScopedTypeVariables

dependencies:
- base >=4.7 && <5
- bytestring
- base16-bytestring
- text
- unordered-containers
- gogol
- gogol-core
- gogol-datastore
- mtl
- lens
- aeson
- vector
- scientific
- cereal
- QuickCheck
- string-conversions
- time
- http-conduit
- exceptions
- monad-control
- resourcet
- transformers-base
- transformers
- async
- errors
- stm
- stm-containers
- hashable
- base64-bytestring
- quickcheck-text
- tagged
- monad-logger
- bitcoin-payment-channel
- promissory-note-types

library:
  source-dirs: src
  ghc-options:
  - -W
  - -Wredundant-constraints
  exposed-modules:
  - ChanDB
  - DB.Model.Convert.Properties
  - Util
tests:
  storage-test:
    main: Storage.hs
    source-dirs: test
    default-extensions:
    - GADTs
    - FlexibleContexts
    - DataKinds
    ghc-options:
    - -Wall
    - -main-is
    - Storage
    - -threaded
    dependencies:
    - paychan-datastore
    - bitcoin-payment-channel
    - promissory-note-types
    - test-framework
    - test-framework-quickcheck2
  conversion-test:
    main: Conversion.hs
    source-dirs: test
    ghc-options:
    - -main-is
    - Conversion
    dependencies:
    - base
    - paychan-datastore
    - HUnit >=1.3
    - QuickCheck >=2.8.2
    - test-framework
    - test-framework-quickcheck2
