name:       paychan-datastore
version:    '0.1.0.0'
synopsis:
description:  Please see README.md
category:     Database Network Google
author:       Rune K. Svendsen
maintainer:   runesvend@gmail.com
copyright:    2016 Rune K. Svendsen
license:      OtherLicense
license-file: LICENSE
github:       runeksvendsen/paychan-datastore

default-extensions:
- OverloadedStrings
- MultiParamTypeClasses
- TypeSynonymInstances
- FlexibleInstances
- FlexibleContexts
- FunctionalDependencies
- DataKinds
- ScopedTypeVariables
- TemplateHaskell

dependencies:
- base >=4.7 && <5
- bytestring
- base16-bytestring
- text
- unordered-containers
- gogol
- gogol-core
- gogol-datastore
- mtl
- lens
- aeson
- vector
- scientific
- cereal
- QuickCheck
- string-conversions
- time
- http-conduit
- exceptions
- monad-control
- resourcet
- transformers-base
- transformers
- async
- errors
- stm
- stm-containers
- hashable
- base64-bytestring
- quickcheck-text
- tagged
- monad-logger
- haskoin-core
- bitcoin-payment-channel
- promissory-note-types
- rbpcp-api
- http-client
- Concurrent-Cache
- fast-logger
- either

library:
  source-dirs: src
  #ghc-options:
  #- -Werror
  exposed-modules:
  - ChanDB
  - DB.Model.Convert.Properties

tests:
  storage:
    main: Storage.hs
    source-dirs: test
    default-extensions:
    - GADTs
    - FlexibleContexts
    - DataKinds
    ghc-options:
    - -main-is
    - Storage
    - -threaded
    dependencies:
    - paychan-datastore
    - test-framework
    - test-framework-quickcheck2
  conversion:
    main: Conversion.hs
    source-dirs: test
    ghc-options:
    #- -Werror
    - -main-is
    - Conversion
    dependencies:
    - paychan-datastore
    - HUnit >=1.3
    - QuickCheck >=2.8.2
    - test-framework
    - test-framework-quickcheck2
