#resolver: nightly-2016-10-29
resolver: nightly-2016-09-15

nix:
  enable: false
  packages: [libtool, automake, lzma]

packages:
- '.'
- location:
    git: https://github.com/runeksvendsen/haskoin.git
    commit: cbc4031f2337f1d7714f55fdd951b9942f8da130
  extra-dep: true
  subdirs:
    - haskoin-core
    - haskoin-node
    - haskoin-wallet
- location:
    git: https://github.com/runeksvendsen/bitcoin-payment-channel.git
    commit: d4c426df4b9b9bd058f2d2d579f97018efce6e15
  extra-dep: true
- location:
    git: https://github.com/brendanhay/gogol.git
    commit: 93f392a2df332dd699528e7ea2422dc892d00971
  extra-dep: true
  subdirs:
    - gogol
    - core
    - gogol-datastore
- location:
    git: https://github.com/runeksvendsen/promissory-note-types.git
    commit: 0ff7e180bf94a9d881b896ed70eb04bb672ef54a
  extra-dep: true
- location:
    git: https://github.com/tsuraan/bytestring-arbitrary.git
    commit: ce6234d7204d8f1faa3a7c05f4802ead210245ce
  extra-dep: true

extra-deps:
- haskoin-core-0.4.0
- murmur3-1.0.3
- pbkdf-1.1.1.1
- secp256k1-0.4.6
- refined-0.1.2.1


# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

